expression_file: "path/to/expression_file.csv"
meta_file: "path/to/meta_file.csv"
output_path: "path/to/output_directory"
reduction_method: "nmf"  # or "pca"
proportion_var_explained: 0.95
num_ranks: -1
min_k: 2
max_k: 7
covariates:
  - "covariate1"
  - "covariate2"
target: "disease"
method: "rf"  # or "xgb"
sub_samp: false
subset_percentage: 0.25
num_cv_repeats: 3
num_outer_splits: 3
num_inner_splits: 5
