name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Miniconda (or Conda) for environment management
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-version: 'latest'  # You can specify a version, but 'latest' is fine
          auto-activate-base: false  # Avoid auto-activation of base environment

      # Create conda environment from environment.yml
      - name: Create conda environment from env.yml
        run: |
          conda env create -f env.yml
          conda activate zhang_lab

      # Run tests
      - name: Run tests with pytest
        run: |
          conda activate zhang_lab
          export PYTHONPATH=$(pwd)  # Set the Python path
          pytest test/  # Run your tests
